name: build
on: [push]
jobs:
  build_job: # job name
    runs-on: ubuntu-22.04
    steps:
      - name: Use JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install libreoffice
        run: sudo apt-get install -y libreoffice

      - name: Standard Checkout
        uses: actions/checkout@v3.2.0

      - name: Use JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -Davispa.ecm.office.home='/usr/lib/libreoffice' -B verify

  generate_badges:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    steps:
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2.9.0
        with:
          generate-branches-badge: true

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions
          message: 'Autogenerated JaCoCo coverage badge'
          add: '*.svg'

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: jacoco-report
          path: target/site/jacoco/